/*
 * This file is generated by jOOQ.
*/
package layers.persistence.jooq;


import javax.annotation.Generated;

import layers.persistence.jooq.tables.Orderline;
import layers.persistence.jooq.tables.Product;
import layers.persistence.jooq.tables.Purchaseorder;
import layers.persistence.jooq.tables.SchemaVersion;
import layers.persistence.jooq.tables.records.OrderlineRecord;
import layers.persistence.jooq.tables.records.ProductRecord;
import layers.persistence.jooq.tables.records.PurchaseorderRecord;
import layers.persistence.jooq.tables.records.SchemaVersionRecord;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OrderlineRecord> ORDERLINE_PKEY = UniqueKeys0.ORDERLINE_PKEY;
    public static final UniqueKey<ProductRecord> PRODUCT_PKEY = UniqueKeys0.PRODUCT_PKEY;
    public static final UniqueKey<PurchaseorderRecord> PURCHASEORDER_PKEY = UniqueKeys0.PURCHASEORDER_PKEY;
    public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = UniqueKeys0.SCHEMA_VERSION_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OrderlineRecord, PurchaseorderRecord> ORDERLINE__ORDERLINE_PURCHASEORDER_ID_FKEY = ForeignKeys0.ORDERLINE__ORDERLINE_PURCHASEORDER_ID_FKEY;
    public static final ForeignKey<OrderlineRecord, ProductRecord> ORDERLINE__ORDERLINE_PRODUCT_ID_FKEY = ForeignKeys0.ORDERLINE__ORDERLINE_PRODUCT_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<OrderlineRecord> ORDERLINE_PKEY = createUniqueKey(Orderline.ORDERLINE, "orderline_pkey", Orderline.ORDERLINE.ID);
        public static final UniqueKey<ProductRecord> PRODUCT_PKEY = createUniqueKey(Product.PRODUCT, "product_pkey", Product.PRODUCT.ID);
        public static final UniqueKey<PurchaseorderRecord> PURCHASEORDER_PKEY = createUniqueKey(Purchaseorder.PURCHASEORDER, "purchaseorder_pkey", Purchaseorder.PURCHASEORDER.ID);
        public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = createUniqueKey(SchemaVersion.SCHEMA_VERSION, "schema_version_pk", SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<OrderlineRecord, PurchaseorderRecord> ORDERLINE__ORDERLINE_PURCHASEORDER_ID_FKEY = createForeignKey(layers.persistence.jooq.Keys.PURCHASEORDER_PKEY, Orderline.ORDERLINE, "orderline__orderline_purchaseorder_id_fkey", Orderline.ORDERLINE.PURCHASEORDER_ID);
        public static final ForeignKey<OrderlineRecord, ProductRecord> ORDERLINE__ORDERLINE_PRODUCT_ID_FKEY = createForeignKey(layers.persistence.jooq.Keys.PRODUCT_PKEY, Orderline.ORDERLINE, "orderline__orderline_product_id_fkey", Orderline.ORDERLINE.PRODUCT_ID);
    }
}
