/*
 * This file is generated by jOOQ.
*/
package layers.persistence.jooq;


import javax.annotation.Generated;

import layers.persistence.jooq.tables.Orderline;
import layers.persistence.jooq.tables.Product;
import layers.persistence.jooq.tables.Purchaseorder;
import layers.persistence.jooq.tables.SchemaVersion;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.orderline</code>.
     */
    public static final Orderline ORDERLINE = layers.persistence.jooq.tables.Orderline.ORDERLINE;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = layers.persistence.jooq.tables.Product.PRODUCT;

    /**
     * The table <code>public.purchaseorder</code>.
     */
    public static final Purchaseorder PURCHASEORDER = layers.persistence.jooq.tables.Purchaseorder.PURCHASEORDER;

    /**
     * The table <code>public.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = layers.persistence.jooq.tables.SchemaVersion.SCHEMA_VERSION;
}
