/*
 * This file is generated by jOOQ.
*/
package layers.persistence.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orderline implements Serializable {

    private static final long serialVersionUID = -842559202;

    private final Long       id;
    private final BigDecimal amount;
    private final Long       purchaseorderId;
    private final Long       productId;

    public Orderline(Orderline value) {
        this.id = value.id;
        this.amount = value.amount;
        this.purchaseorderId = value.purchaseorderId;
        this.productId = value.productId;
    }

    public Orderline(
        Long       id,
        BigDecimal amount,
        Long       purchaseorderId,
        Long       productId
    ) {
        this.id = id;
        this.amount = amount;
        this.purchaseorderId = purchaseorderId;
        this.productId = productId;
    }

    public Long getId() {
        return this.id;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public Long getPurchaseorderId() {
        return this.purchaseorderId;
    }

    public Long getProductId() {
        return this.productId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orderline (");

        sb.append(id);
        sb.append(", ").append(amount);
        sb.append(", ").append(purchaseorderId);
        sb.append(", ").append(productId);

        sb.append(")");
        return sb.toString();
    }
}
