/*
 * This file is generated by jOOQ.
*/
package layers.persistence.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product implements Serializable {

    private static final long serialVersionUID = -19646334;

    private final Long      id;
    private final Long      version;
    private final Timestamp createtime;
    private final String    name;

    public Product(Product value) {
        this.id = value.id;
        this.version = value.version;
        this.createtime = value.createtime;
        this.name = value.name;
    }

    public Product(
        Long      id,
        Long      version,
        Timestamp createtime,
        String    name
    ) {
        this.id = id;
        this.version = version;
        this.createtime = createtime;
        this.name = name;
    }

    public Long getId() {
        return this.id;
    }

    public Long getVersion() {
        return this.version;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product (");

        sb.append(id);
        sb.append(", ").append(version);
        sb.append(", ").append(createtime);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
