/*
 * This file is generated by jOOQ.
*/
package layers.persistence.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Purchaseorder implements Serializable {

    private static final long serialVersionUID = -1970756952;

    private final Long      id;
    private final Long      version;
    private final Timestamp createtime;

    public Purchaseorder(Purchaseorder value) {
        this.id = value.id;
        this.version = value.version;
        this.createtime = value.createtime;
    }

    public Purchaseorder(
        Long      id,
        Long      version,
        Timestamp createtime
    ) {
        this.id = id;
        this.version = version;
        this.createtime = createtime;
    }

    public Long getId() {
        return this.id;
    }

    public Long getVersion() {
        return this.version;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Purchaseorder (");

        sb.append(id);
        sb.append(", ").append(version);
        sb.append(", ").append(createtime);

        sb.append(")");
        return sb.toString();
    }
}
