/*
 * This file is generated by jOOQ.
*/
package layers.persistence.jooq.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import layers.persistence.jooq.tables.Orderline;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlineRecord extends UpdatableRecordImpl<OrderlineRecord> implements Record4<Long, BigDecimal, Long, Long> {

    private static final long serialVersionUID = 756657496;

    /**
     * Setter for <code>public.orderline.id</code>.
     */
    public OrderlineRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.orderline.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.orderline.amount</code>.
     */
    public OrderlineRecord setAmount(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.orderline.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.orderline.purchaseorder_id</code>.
     */
    public OrderlineRecord setPurchaseorderId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.orderline.purchaseorder_id</code>.
     */
    public Long getPurchaseorderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.orderline.product_id</code>.
     */
    public OrderlineRecord setProductId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.orderline.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, BigDecimal, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, BigDecimal, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Orderline.ORDERLINE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return Orderline.ORDERLINE.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Orderline.ORDERLINE.PURCHASEORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Orderline.ORDERLINE.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPurchaseorderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value2(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value3(Long value) {
        setPurchaseorderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value4(Long value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord values(Long value1, BigDecimal value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlineRecord
     */
    public OrderlineRecord() {
        super(Orderline.ORDERLINE);
    }

    /**
     * Create a detached, initialised OrderlineRecord
     */
    public OrderlineRecord(Long id, BigDecimal amount, Long purchaseorderId, Long productId) {
        super(Orderline.ORDERLINE);

        set(0, id);
        set(1, amount);
        set(2, purchaseorderId);
        set(3, productId);
    }
}
