/*
 * This file is generated by jOOQ.
*/
package layers.persistence.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import layers.persistence.jooq.tables.Purchaseorder;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseorderRecord extends UpdatableRecordImpl<PurchaseorderRecord> implements Record3<Long, Long, Timestamp> {

    private static final long serialVersionUID = 2110280694;

    /**
     * Setter for <code>public.purchaseorder.id</code>.
     */
    public PurchaseorderRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.purchaseorder.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.purchaseorder.version</code>.
     */
    public PurchaseorderRecord setVersion(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.purchaseorder.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.purchaseorder.createtime</code>.
     */
    public PurchaseorderRecord setCreatetime(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.purchaseorder.createtime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Purchaseorder.PURCHASEORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Purchaseorder.PURCHASEORDER.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Purchaseorder.PURCHASEORDER.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseorderRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseorderRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseorderRecord value3(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseorderRecord values(Long value1, Long value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseorderRecord
     */
    public PurchaseorderRecord() {
        super(Purchaseorder.PURCHASEORDER);
    }

    /**
     * Create a detached, initialised PurchaseorderRecord
     */
    public PurchaseorderRecord(Long id, Long version, Timestamp createtime) {
        super(Purchaseorder.PURCHASEORDER);

        set(0, id);
        set(1, version);
        set(2, createtime);
    }
}
