/*
 * This file is generated by jOOQ.
*/
package layers.persistence.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import layers.persistence.jooq.Keys;
import layers.persistence.jooq.Public;
import layers.persistence.jooq.tables.records.OrderlineRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orderline extends TableImpl<OrderlineRecord> {

    private static final long serialVersionUID = 2088099449;

    /**
     * The reference instance of <code>public.orderline</code>
     */
    public static final Orderline ORDERLINE = new Orderline();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlineRecord> getRecordType() {
        return OrderlineRecord.class;
    }

    /**
     * The column <code>public.orderline.id</code>.
     */
    public final TableField<OrderlineRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.orderline.amount</code>.
     */
    public final TableField<OrderlineRecord, BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.NUMERIC.precision(19, 2), this, "");

    /**
     * The column <code>public.orderline.purchaseorder_id</code>.
     */
    public final TableField<OrderlineRecord, Long> PURCHASEORDER_ID = createField("purchaseorder_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.orderline.product_id</code>.
     */
    public final TableField<OrderlineRecord, Long> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.orderline</code> table reference
     */
    public Orderline() {
        this("orderline", null);
    }

    /**
     * Create an aliased <code>public.orderline</code> table reference
     */
    public Orderline(String alias) {
        this(alias, ORDERLINE);
    }

    private Orderline(String alias, Table<OrderlineRecord> aliased) {
        this(alias, aliased, null);
    }

    private Orderline(String alias, Table<OrderlineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrderlineRecord> getPrimaryKey() {
        return Keys.ORDERLINE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrderlineRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderlineRecord>>asList(Keys.ORDERLINE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrderlineRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrderlineRecord, ?>>asList(Keys.ORDERLINE__ORDERLINE_PURCHASEORDER_ID_FKEY, Keys.ORDERLINE__ORDERLINE_PRODUCT_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Orderline as(String alias) {
        return new Orderline(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Orderline rename(String name) {
        return new Orderline(name, null);
    }
}
