/*
 * This file is generated by jOOQ.
*/
package layers.persistence.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import layers.persistence.jooq.Keys;
import layers.persistence.jooq.Public;
import layers.persistence.jooq.tables.records.PurchaseorderRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Purchaseorder extends TableImpl<PurchaseorderRecord> {

    private static final long serialVersionUID = -2026675919;

    /**
     * The reference instance of <code>public.purchaseorder</code>
     */
    public static final Purchaseorder PURCHASEORDER = new Purchaseorder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PurchaseorderRecord> getRecordType() {
        return PurchaseorderRecord.class;
    }

    /**
     * The column <code>public.purchaseorder.id</code>.
     */
    public final TableField<PurchaseorderRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.purchaseorder.version</code>.
     */
    public final TableField<PurchaseorderRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.purchaseorder.createtime</code>.
     */
    public final TableField<PurchaseorderRecord, Timestamp> CREATETIME = createField("createtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("('now'::text)::timestamp without time zone", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>public.purchaseorder</code> table reference
     */
    public Purchaseorder() {
        this("purchaseorder", null);
    }

    /**
     * Create an aliased <code>public.purchaseorder</code> table reference
     */
    public Purchaseorder(String alias) {
        this(alias, PURCHASEORDER);
    }

    private Purchaseorder(String alias, Table<PurchaseorderRecord> aliased) {
        this(alias, aliased, null);
    }

    private Purchaseorder(String alias, Table<PurchaseorderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PurchaseorderRecord> getPrimaryKey() {
        return Keys.PURCHASEORDER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PurchaseorderRecord>> getKeys() {
        return Arrays.<UniqueKey<PurchaseorderRecord>>asList(Keys.PURCHASEORDER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Purchaseorder as(String alias) {
        return new Purchaseorder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Purchaseorder rename(String name) {
        return new Purchaseorder(name, null);
    }
}
